### ISSUE TITLE
Is that any paper associated with this repo?

### ISSUE THREAD

**Issue by Vandermode** [thangvubk/FEQE#2]
Hi, I'm very interested with this work and its amazing results. 
I was wondering is there a paper related to it since I can only find the description in [1].

[1] PIRM Challenge on Perceptual Image Enhancement on Smartphones: Report

**Comment by thangvubk** [comment]
Thank you for your interest. Yes, there is. It will be released soon. I will update readme then.

**Comment by Vandermode** [comment]
Thank you for your immediate helpful reply！

**Comment by chaos5958** [comment]
Also, I'm waiting for this paper, but I have one question.

Suppose we want to upscale from 360p to 1080p (x3).
Does desubpixel mean that we can further reduce resolution by 180p and then later upscale to 1080p (x6)?
Since the image shown in the README applies for image enhancement of the same resolution image pair.
If this is correct, it would be awesome to reduce computational complexity similar to that classification/detection reduce resolution for enhancing processing latency.

**Comment by thangvubk** [comment]
This repo follows the policy of PIRM smartphone competition where the considered LR is already interpolated. Theoretically, you can downsample one more time (as you mentioned) to reduce complexity. The philosophy here is using invertible downsampling to mitigate negative effects of downsampling operation.

**Comment by chaos5958** [comment]
Thank you, I just want to know that it could also apply to common LR, HR settings (LR -- NETWORK -- SUBPIXEL CONVOLUTION -- HR).
Have you tried with low-resolution images without interpolation?

**Comment by thangvubk** [comment]
I am currently busy with another project. You are encouraged to investigate your idea. I think it is feasible. If you have some meaningful results, pls share with us :)
