### ISSUE TITLE
Out of memory of cpu with 32GB 

### ISSUE THREAD

**Issue by Rainyfish** [thangvubk/FEQE#3]
When producing the .npz file. program will exit with out of memory. But my computer has 32GB cup memory. How larger is your CPU memory?

**Comment by thangvubk** [comment]
If I'm not wrong, you mentioned out of memory in RAM. My server has 128G RAM. For the first run, it takes quite much memory for the writing operation.  I have some suggestions for u:
1. Try to train with half of the training dataset.
2. You can load directly from images instead of writing to a bin file but it might be much slower in training.

**Comment by Rainyfish** [comment]
Thank you for your suggestions, I will transform every image to .npz files and load the all the npz file in the RAM. Or can you  release the .npz files that you built in your machine?

**Comment by thangvubk** [comment]
Since the bin files are also big, please try the suggestions first to see if they help or not :D
