### ISSUE TITLE
Why didn't you try it in GAN-based approach?

### ISSUE THREAD

**Issue by Oktai15** [thangvubk/FEQE#5]
Thank you for interesting paper and great work, @thangvubk!

I wonder why no one from challenge didn't try to train light-weight model with discriminator? Indeed, complexity would grow, but only in training time, not in inference. Moreover, as far as I know, adversarial way increases perceptual quality...

What do you think it's simple to train your model with discriminator to improve results?

**Comment by cao-nv** [comment]
Actually, as you said adversarial training can help to improve the perceptual quality. 
IMHO, there may be some fundamental problems when using that method: 
1. High perceptual quality does not mean low reconstruction loss. Everyone optimize their model for the given dataset only. 
2. When you training an adversarial model, you would need a huge amount of data to be able to cover all the data distribution, otherwise, you can not get well trained 
3. Adversarial models (i.e GANs) are very difficult to train

**Comment by Oktai15** [comment]
@cao-nv okay, it's interesting that no one in challenge didn't try it. 

Currently, all models that I saw and that use GAN-based approach very huge and we have no chance to port it on device. What do you think it's really impossible to train light-weight model as generator or what is the reason?

**Comment by thangvubk** [comment]
@Oktai15 Thank you for your interest.

Not choosing GAN-based for the PIRM 2018 mobile SR competition is our strategy and perhaps the others. The reason is:
- On mobile devices, we need to tradeoff between speed and reconstruction. Since the reconstruction has some limitation, applying GAN is not our choice. I experienced that GAN help improves texture when we have very good reconstruction but it is not this case. 
- If you are interesting in applying GAN for mobile device, you can try to relax the problem to SR with scale factor x2. Porting to mobile devices is not a problem because you can remove the discriminator after training.

**Comment by Oktai15** [comment]
@thangvubk a lot of thanks for your answer!

About first point: “but it is not this case” — you mean that you tried to train your model with discriminator but is didn’t help?

Actually, I am very interested to train lightweight model (e.g your model) with discriminator so that improve perceptual quality, but confused that I can’t find paper where people try it. Maybe small generator is very hard limitation, what do you think?

**Comment by cao-nv** [comment]
@Oktai15 
Additionally, since the generator is much larger than the discriminator, the model is still very large even when the discriminator is removed.
In [Optimizing the Latent Space for Generative Networks](http://proceedings.mlr.press/v80/bojanowski18a/bojanowski18a.pdf), the authors suggest that most properties of GANs come from the flexibility of deep networks, not from the adversarial training procedure.

**Comment by thangvubk** [comment]
@Oktai15 "it is not this case": i mean we dont have desired reconstruction quality to apply GAN. Actually, that is only our strategy, you can try it :D

**Comment by Oktai15** [comment]
@cao-nv oh, that’s really reason. Thank you for paper!

@thangvubk oh, I understood: your goal was a reconstruction measure only. Hm, okay. I need to try dicriminator anyway :)

**Comment by novioleo** [comment]
> @cao-nv okay, it's interesting that no one in challenge didn't try it.
> 
> Currently, all models that I saw and that use GAN-based approach very huge and we have no chance to port it on device. What do you think it's really impossible to train light-weight model as generator or what is the reason?

i think there are some person have tried...similar with DPED.

**Comment by Oktai15** [comment]
@novioleo can you give me links to these works?

**Comment by novioleo** [comment]
> @novioleo can you give me links to these works?

you can search `TOPIC` image enhance related on github,or search some **AWESOME** projects to have a overview...
